### ISSUE TITLE
\" is again getting escaped and making the pattern invalid

### ISSUE THREAD

**Issue by Sharathnasa** [google/re2j#120]
Hi Team,

I'm creating the regex as - "^[\\w\\d!@#$%^(){}:;<>**\".**|/?=+-]+$"

Here i'm having the double quote already escaped. But when i try to build using re2j, its again escaping the string as shown below and making the pattern invalid(That, not pattern is ending at \" itself)

![Screenshot 2020-10-18 at 12 48 28 PM](https://user-images.githubusercontent.com/7545011/96361116-aba18300-1140-11eb-8fae-aff2ff4291d7.png)

com.google.re2j.Pattern GLOBAL_TRADE_ITEM_NUMBER__PATTERN = com.google.re2j.Pattern.compile("^[\\w\\d!@#$%^(){}:;<>.|/?=\\"+-]+$");

![Screenshot 2020-10-18 at 12 47 11 PM](https://user-images.githubusercontent.com/7545011/96361107-a17f8480-1140-11eb-82b8-0cf5056b59dc.png)

Now it's again esacping as highlighted above its thinking that esacaping is for backslash and not for " and thinking " is the end of pattern and making the 

next characterts invalid. I think here github is unescaping. I'll attache screenshot aslo.

Regards,
Sharath

**Comment by sjamesr** [comment]
Though you never say so explicitly, it looks like you are using the protocol buffer compiler to generate Java code. You need to tell the protocol buffer compiler to emit a backslash before the double quotes, then emit a literal double quote, so I would write: `\\\"`. instead of `\"` in your protocol buffer definition.

Anyway, this is not an RE2J issue, you have a problem in the code that calls into RE2J.
